/**
 * Pluggable pipeline registry.
 *
 * Each executor receives a single step description plus shared context and
 * returns the logs printed by the "tool" and a set of artifacts it produced.
 *
 * Artifacts are returned as base64 to be streamed back to the browser, where
 * they become `data:` URLs that can be downloaded directly. Replace any of
 * these mock executors with a real call to your compute backend (Slurm, k8s
 * jobs, RunPod, AWS Batch, internal HTTP API, etc.) without touching the
 * route or the UI — just keep the return shape.
 *
 * ── LangGraph Integration Interface ─────────────────────────────────────────
 * When the ADADD LangGraph DAG backend is ready, replace mock executors with
 * HTTP calls to the Python LangGraph service. Keep StepExecutor signature.
 *
 * Python-side LangGraph node example (mabpoc/orchestration/nodes/):
 *
 *   from mabpoc.orchestration.nodes import structure_prediction_node
 *   from langgraph.graph import StateGraph
 *
 *   graph = StateGraph(ADAddState)
 *   graph.add_node("structure_prediction", structure_prediction_node)
 *   graph.add_node("mutation_generation", mutation_generation_node)
 *   # ... add all 8 ADADD agent nodes
 *   graph.add_conditional_edges("affinity_scoring", odbo_router)
 *   app = graph.compile()
 *
 * TypeScript caller (replace mock executors below):
 *
 *   const langGraphExecutor: StepExecutor = async (step, ctx) => {
 *     const res = await fetch(`${LANGGRAPH_BASE_URL}/runs`, {
 *       method: "POST",
 *       headers: { "Content-Type": "application/json" },
 *       body: JSON.stringify({
 *         assistant_id: "adadd-pipeline",
 *         input: { step: step.name, tool: step.tool, ...ctx },
 *       }),
 *     });
 *     const { output } = await res.json();
 *     return { logs: output.logs, artifacts: output.artifacts };
 *   };
 *
 * Set LANGGRAPH_BASE_URL=http://localhost:8123 in .env to activate.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import type { ComputationPlan, PlanStep } from "./types";

export type PipelineContext = {
  jobId: string;
  plan: ComputationPlan;
  target: string;
  method: string;
  stepIndex: number;
};

export type StepArtifact = {
  name: string;
  mime: string;
  dataBase64: string;
};

export type StepResult = {
  logs: string;
  artifacts: StepArtifact[];
};

export type StepExecutor = (
  step: PlanStep,
  ctx: PipelineContext,
) => Promise<StepResult>;

function toBase64(text: string): string {
  // Web-runtime safe (Workers). btoa handles latin1 only, so encode to bytes first.
  const bytes = new TextEncoder().encode(text);
  let binary = "";
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

function randf(min: number, max: number): number {
  return Math.round((min + Math.random() * (max - min)) * 1000) / 1000;
}

const alphafoldExecutor: StepExecutor = async (step, ctx) => {
  // Minimal PDB stub — enough to open in PyMOL / Mol* viewer.
  const pdb = [
    `HEADER    PREDICTED MODEL (MOCK)              ${new Date().toISOString().slice(0, 10)}`,
    `TITLE     ${ctx.plan.title} — ${ctx.target}`,
    `REMARK   1 GENERATED BY ADADD PIPELINE (${step.tool})`,
    `REMARK   2 pLDDT_MEAN ${randf(70, 92)}`,
    `ATOM      1  N   MET A   1      11.104  13.207  10.453  1.00 85.32           N`,
    `ATOM      2  CA  MET A   1      12.560  13.207  10.453  1.00 85.32           C`,
    `ATOM      3  C   MET A   1      13.115  14.611  10.453  1.00 85.32           C`,
    `ATOM      4  O   MET A   1      12.412  15.617  10.453  1.00 85.32           O`,
    `TER`,
    `END`,
  ].join("\n");
  return {
    logs:
      `[${step.tool}] 加载序列：${ctx.target}\n` +
      `[${step.tool}] 模板检索完成（mock）\n` +
      `[${step.tool}] MSA 深度 = ${Math.floor(randf(120, 480))}\n` +
      `[${step.tool}] 推理完成，pLDDT_mean ≈ ${randf(70, 92)}\n` +
      `[${step.tool}] 输出结构：predicted.pdb`,
    artifacts: [
      { name: `${ctx.target.replace(/\W+/g, "_")}_predicted.pdb`, mime: "chemical/x-pdb", dataBase64: toBase64(pdb) },
    ],
  };
};

const dockingExecutor: StepExecutor = async (step, ctx) => {
  const rows = ["ligand_id,pose,affinity_kcal_per_mol,rmsd_lb,rmsd_ub"];
  const n = 12;
  for (let i = 1; i <= n; i++) {
    for (let p = 1; p <= 3; p++) {
      rows.push(`LIG_${String(i).padStart(3, "0")},${p},${randf(-11.4, -5.2)},${randf(0, 2.3)},${randf(0.5, 3.8)}`);
    }
  }
  const csv = rows.join("\n");
  return {
    logs:
      `[${step.tool}] 受体：${ctx.target}\n` +
      `[${step.tool}] 配体库：${n} 个分子\n` +
      `[${step.tool}] 网格盒子：22 x 22 x 22 Å\n` +
      `[${step.tool}] 穷举度 = 8，每分子 3 个最佳构象\n` +
      `[${step.tool}] 对接完成，输出：docking_results.csv`,
    artifacts: [
      { name: "docking_results.csv", mime: "text/csv", dataBase64: toBase64(csv) },
    ],
  };
};

const rdkitExecutor: StepExecutor = async (step, ctx) => {
  const samples = [
    { id: "LIG_001", smiles: "CC(=O)Oc1ccccc1C(=O)O", mw: 180.16, logp: 1.19 },
    { id: "LIG_002", smiles: "CN1C=NC2=C1C(=O)N(C(=O)N2C)C", mw: 194.19, logp: -0.07 },
    { id: "LIG_003", smiles: "CC(C)Cc1ccc(C(C)C(=O)O)cc1", mw: 206.28, logp: 3.97 },
  ];
  const rows = ["id,smiles,mol_weight,logp,h_donors,h_acceptors,rot_bonds,lipinski_pass"];
  for (const s of samples) {
    rows.push(
      `${s.id},${s.smiles},${s.mw},${s.logp},${Math.floor(randf(0, 4))},${Math.floor(randf(1, 8))},${Math.floor(randf(0, 8))},true`,
    );
  }
  return {
    logs:
      `[${step.tool}] 解析 ${samples.length} 个 SMILES\n` +
      `[${step.tool}] 计算描述符 (MW, logP, HBD, HBA, RotB)\n` +
      `[${step.tool}] Lipinski 规则筛选：${samples.length} 通过\n` +
      `[${step.tool}] 输出：descriptors.csv`,
    artifacts: [
      { name: "descriptors.csv", mime: "text/csv", dataBase64: toBase64(rows.join("\n")) },
    ],
  };
};

const mdExecutor: StepExecutor = async (step, ctx) => {
  const ns = 50;
  const rows = ["time_ns,rmsd_A,rg_A,sasa_A2,energy_kJ_per_mol"];
  for (let t = 0; t <= ns; t++) {
    rows.push(`${t},${randf(0.8, 2.4)},${randf(14, 16)},${randf(11200, 12800)},${randf(-580000, -540000)}`);
  }
  return {
    logs:
      `[${step.tool}] 体系：${ctx.target} + ${ctx.method}\n` +
      `[${step.tool}] 力场：AMBER ff14SB / TIP3P 水盒子\n` +
      `[${step.tool}] NPT 平衡完成（100 ps）\n` +
      `[${step.tool}] 生产模拟 ${ns} ns 完成\n` +
      `[${step.tool}] 轨迹分析：RMSD/Rg/SASA → trajectory_summary.csv`,
    artifacts: [
      { name: "trajectory_summary.csv", mime: "text/csv", dataBase64: toBase64(rows.join("\n")) },
    ],
  };
};

const genericExecutor: StepExecutor = async (step, ctx) => {
  const report = {
    job_id: ctx.jobId,
    step: step.name,
    tool: step.tool,
    target: ctx.target,
    method: ctx.method,
    inputs: step.inputs,
    outputs: step.outputs,
    metrics: {
      duration_seconds: Math.floor(randf(8, 40)),
      score: randf(0.62, 0.94),
    },
    notes:
      "这是一个由 ADADD 平台生成的演示工件。要接入真实计算后端，请实现 src/lib/pipelines.server.ts 中的 executor 接口。",
    generated_at: new Date().toISOString(),
  };
  return {
    logs:
      `[${step.tool}] 启动通用执行器\n` +
      `[${step.tool}] 输入：${step.inputs}\n` +
      `[${step.tool}] 输出：${step.outputs}\n` +
      `[${step.tool}] 完成，分数 = ${report.metrics.score}`,
    artifacts: [
      {
        name: `${step.tool.replace(/\W+/g, "_")}_result.json`,
        mime: "application/json",
        dataBase64: toBase64(JSON.stringify(report, null, 2)),
      },
    ],
  };
};

/**
 * Pluggable registry. Match against the step's `tool` name (case-insensitive
 * substring). Add new entries here to wire real backends.
 */
const REGISTRY: { match: RegExp; executor: StepExecutor; label: string }[] = [
  { match: /alphafold|esm|esmfold|rosettafold|openfold/i, executor: alphafoldExecutor, label: "结构预测" },
  { match: /autodock|vina|diffdock|smina|gnina|dock/i, executor: dockingExecutor, label: "分子对接" },
  { match: /rdkit|openbabel|descriptors?/i, executor: rdkitExecutor, label: "化学信息学" },
  { match: /gromacs|openmm|amber|namd|md\b|molecular dynamics/i, executor: mdExecutor, label: "分子动力学" },
];

export function getExecutor(toolName: string): { executor: StepExecutor; label: string } {
  for (const entry of REGISTRY) {
    if (entry.match.test(toolName)) return { executor: entry.executor, label: entry.label };
  }
  return { executor: genericExecutor, label: "通用执行器" };
}

/** Simulated wall-clock per step. Real backends should remove this. */
export function stepDurationMs(step: PlanStep): number {
  // Compress the LLM-estimated minutes into a few seconds for demo runs.
  const minutes = Math.max(1, step.estimated_minutes || 1);
  return Math.min(6000, 800 + minutes * 120);
}