/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WetlabRouteImport } from './routes/wetlab'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FilesRouteImport } from './routes/files'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CThreadIdRouteImport } from './routes/c.$threadId'
import { Route as ApiRunRouteImport } from './routes/api/run'
import { Route as ApiRagRouteImport } from './routes/api/rag'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WetlabRoute = WetlabRouteImport.update({
  id: '/wetlab',
  path: '/wetlab',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CThreadIdRoute = CThreadIdRouteImport.update({
  id: '/c/$threadId',
  path: '/c/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunRoute = ApiRunRouteImport.update({
  id: '/api/run',
  path: '/api/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRagRoute = ApiRagRouteImport.update({
  id: '/api/rag',
  path: '/api/rag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/reports': typeof ReportsRoute
  '/wetlab': typeof WetlabRoute
  '/api/chat': typeof ApiChatRoute
  '/api/rag': typeof ApiRagRoute
  '/api/run': typeof ApiRunRoute
  '/c/$threadId': typeof CThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/reports': typeof ReportsRoute
  '/wetlab': typeof WetlabRoute
  '/api/chat': typeof ApiChatRoute
  '/api/rag': typeof ApiRagRoute
  '/api/run': typeof ApiRunRoute
  '/c/$threadId': typeof CThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/reports': typeof ReportsRoute
  '/wetlab': typeof WetlabRoute
  '/api/chat': typeof ApiChatRoute
  '/api/rag': typeof ApiRagRoute
  '/api/run': typeof ApiRunRoute
  '/c/$threadId': typeof CThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/files'
    | '/jobs'
    | '/reports'
    | '/wetlab'
    | '/api/chat'
    | '/api/rag'
    | '/api/run'
    | '/c/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/files'
    | '/jobs'
    | '/reports'
    | '/wetlab'
    | '/api/chat'
    | '/api/rag'
    | '/api/run'
    | '/c/$threadId'
  id:
    | '__root__'
    | '/'
    | '/files'
    | '/jobs'
    | '/reports'
    | '/wetlab'
    | '/api/chat'
    | '/api/rag'
    | '/api/run'
    | '/c/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilesRoute: typeof FilesRoute
  JobsRoute: typeof JobsRoute
  ReportsRoute: typeof ReportsRoute
  WetlabRoute: typeof WetlabRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiRagRoute: typeof ApiRagRoute
  ApiRunRoute: typeof ApiRunRoute
  CThreadIdRoute: typeof CThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wetlab': {
      id: '/wetlab'
      path: '/wetlab'
      fullPath: '/wetlab'
      preLoaderRoute: typeof WetlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$threadId': {
      id: '/c/$threadId'
      path: '/c/$threadId'
      fullPath: '/c/$threadId'
      preLoaderRoute: typeof CThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run': {
      id: '/api/run'
      path: '/api/run'
      fullPath: '/api/run'
      preLoaderRoute: typeof ApiRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rag': {
      id: '/api/rag'
      path: '/api/rag'
      fullPath: '/api/rag'
      preLoaderRoute: typeof ApiRagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilesRoute: FilesRoute,
  JobsRoute: JobsRoute,
  ReportsRoute: ReportsRoute,
  WetlabRoute: WetlabRoute,
  ApiChatRoute: ApiChatRoute,
  ApiRagRoute: ApiRagRoute,
  ApiRunRoute: ApiRunRoute,
  CThreadIdRoute: CThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
